package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var exportCmd = &cobra.Command{
	Use:   "export [target]",
	Short: "Export structural metadata for an AI agent",
	Long: `Export Lea's structural metadata and reasoning protocols to agent-specific configuration files.
Supported targets: claude, cursor, opencode, codex, gemini, pi, antigravity, copilot, aider, openhands, continue.`,
	Args: cobra.ExactArgs(1),
	RunE: func(_ *cobra.Command, args []string) error {
		target := args[0]
		path := "." // Default to current directory

		switch target {
		case "claude":
			return exportClaude(path)
		case "cursor":
			return exportCursor(path)
		case "opencode":
			return exportOpenCode(path)
		case "codex":
			return exportCodex(path)
		case "gemini":
			return exportGemini(path)
		case "pi":
			return exportPi(path)
		case "antigravity":
			return exportAntigravity(path)
		case "copilot":
			return exportCopilot(path)
		case "aider":
			return exportAider(path)
		case "openhands":
			return exportOpenHands(path)
		case "continue":
			return exportContinue(path)
		default:
			return fmt.Errorf("unsupported export target: %s", target)
		}
	},
}

func exportClaude(path string) error {
	content := `# CLAUDE.md

## Structural Reasoning

This repository uses [Lea](https://github.com/PizenLabs/lea) for structural reasoning.

Before performing complex refactoring or impact analysis, refer to the [.lea/AGENT.md](.lea/AGENT.md) for the recommended reasoning protocol.

Lea provides a deterministic structural graph that should be used to:
- Trace call hierarchies.
- Analyze dependency blast radius.
- Validate architecture constraints.
`
	filePath := filepath.Join(path, "CLAUDE.md")
	fmt.Printf("Exporting for Claude to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportCursor(path string) error {
	content := `# Lea Structural Reasoning

This repository contains a structural graph generated by Lea.

## Reasoning Workflow

1. Use Lea CLI to discover symbols and their relationships.
2. Inspect structural dependencies before reading source files.
3. Follow the protocol in [.lea/AGENT.md](.lea/AGENT.md).

## Capabilities
- Symbol Discovery: Find exact locations of types and functions.
- Impact Analysis: Determine what will break if a symbol changes.
- Call Graph: Navigate execution paths deterministically.
`
	dirPath := filepath.Join(path, ".cursor", "rules")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "lea.mdc")
	fmt.Printf("Exporting for Cursor to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportOpenCode(path string) error {
	content := `# Structural Reasoning Protocol

Refer to [.lea/AGENT.md](.lea/AGENT.md) for detailed structural reasoning instructions.
`
	dirPath := filepath.Join(path, ".opencode")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "AGENTS.md")
	fmt.Printf("Exporting for OpenCode to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportCodex(path string) error {
	content := `# Structural Reasoning Protocol

Refer to [.lea/AGENT.md](.lea/AGENT.md) for detailed structural reasoning instructions.
`
	dirPath := filepath.Join(path, ".codex")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "AGENTS.md")
	fmt.Printf("Exporting for Codex to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportGemini(path string) error {
	content := `# GEMINI.md

## Structural Reasoning

This repository uses [Lea](https://github.com/PizenLabs/lea) for structural reasoning.

Before performing complex refactoring or impact analysis, refer to the [.lea/AGENT.md](.lea/AGENT.md) for the recommended reasoning protocol.
`
	filePath := filepath.Join(path, "GEMINI.md")
	fmt.Printf("Exporting for Gemini CLI to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportPi(path string) error {
	content := `# Structural Reasoning Protocol

Refer to [.lea/AGENT.md](.lea/AGENT.md) for detailed structural reasoning instructions.
`
	dirPath := filepath.Join(path, ".pi")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "AGENTS.md")
	fmt.Printf("Exporting for Pi Agents to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportAntigravity(path string) error {
	content := `# Structural Reasoning Protocol

Refer to [.lea/AGENT.md](.lea/AGENT.md) for detailed structural reasoning instructions.
`
	dirPath := filepath.Join(path, ".antigravity")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "AGENTS.md")
	fmt.Printf("Exporting for Antigravity CLI to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportCopilot(path string) error {
	content := `# GitHub Copilot Structural Reasoning

This repository uses Lea for structural reasoning.

## Reasoning Protocol
Refer to [.lea/AGENT.md](.lea/AGENT.md) for the recommended reasoning workflow.

## Guidelines
- Use Lea tools to identify symbol locations and dependencies.
- Avoid large-scale file reads; prefer structural context.
`
	dirPath := filepath.Join(path, ".github")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "copilot-instructions.md")
	fmt.Printf("Exporting for GitHub Copilot to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportAider(path string) error {
	content := `# Aider Structural Reasoning

Refer to [.lea/AGENT.md](.lea/AGENT.md) for the recommended reasoning protocol.
`
	filePath := filepath.Join(path, "CONVENTIONS.md")
	fmt.Printf("Exporting for Aider to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportOpenHands(path string) error {
	content := `name: lea
description: Structural reasoning via Lea
instructions: |
  Before inspecting source files, follow the structural reasoning protocol in .lea/AGENT.md.
  Use Lea CLI tools to discover symbols, analyze dependencies, and trace call graphs.
`
	dirPath := filepath.Join(path, ".openhands", "microagents")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "lea.yaml")
	fmt.Printf("Exporting for OpenHands to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func exportContinue(path string) error {
	content := `# Lea Structural Reasoning

Follow the reasoning protocol in [.lea/AGENT.md](.lea/AGENT.md) for all structural analysis tasks.
`
	dirPath := filepath.Join(path, ".continue", "rules")
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return err
	}

	filePath := filepath.Join(dirPath, "lea.md")
	fmt.Printf("Exporting for Continue to %s...\n", filePath)
	return os.WriteFile(filePath, []byte(content), 0644)
}

func init() {
	rootCmd.AddCommand(exportCmd)
}
