package commands

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	graph "github.com/PizenLabs/lea/internal/graph/contracts"
	"github.com/PizenLabs/lea/internal/parser/golang"
	"github.com/PizenLabs/lea/internal/parser/treesitter"
	"github.com/PizenLabs/lea/internal/storage/contracts"
	"github.com/PizenLabs/lea/internal/storage/sqlite"
	"github.com/PizenLabs/lea/internal/workspace/ignore"
	"github.com/spf13/cobra"
)

var indexCmd = &cobra.Command{
	Use:   "index [path]",
	Short: "Index a repository",
	Args:  cobra.MaximumNArgs(1),
	RunE: func(_ *cobra.Command, args []string) error {
		path := "."
		if len(args) > 0 {
			path = args[0]
		}

		// Ensure .lea directory exists
		leaDir := filepath.Join(path, ".lea")
		if _, err := os.Stat(leaDir); os.IsNotExist(err) {
			if err := os.Mkdir(leaDir, 0755); err != nil {
				return fmt.Errorf("failed to create .lea directory: %w", err)
			}
		}

		dbPath := filepath.Join(leaDir, "graph.db")
		store, err := sqlite.NewStore(dbPath)
		if err != nil {
			return err
		}
		defer func() { _ = store.Close() }()

		goParser := golang.NewParser()
		if modName := getModuleName(path); modName != "" {
			goParser.SetModuleName(modName)
		}
		tsParser := treesitter.NewParser()
		ctx := context.Background()
		matcher := ignore.NewMatcher(path)

		err = filepath.WalkDir(path, func(filePath string, entry fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				if matcher.ShouldSkipDir(filePath, entry) {
					return filepath.SkipDir
				}
				return nil
			}
			if matcher.ShouldSkipFile(filePath, entry) {
				return nil
			}

			var nodes []*graph.Node
			var edges []*graph.Edge

			ext := strings.ToLower(filepath.Ext(filePath))
			switch ext {
			case ".go":
				var parseErr error
				nodes, edges, parseErr = goParser.ParseFile(ctx, filePath)
				if parseErr != nil {
					return fmt.Errorf("parse %s: %w", filePath, parseErr)
				}
				callEdges, callErr := goParser.ExtractCalls(ctx, filePath)
				if callErr != nil {
					return fmt.Errorf("extract calls %s: %w", filePath, callErr)
				}
				flowEdges, flowErr := goParser.ExtractControlFlow(ctx, filePath)
				if flowErr != nil {
					return fmt.Errorf("extract flow %s: %w", filePath, flowErr)
				}
				edges = append(edges, callEdges...)
				edges = append(edges, flowEdges...)
			case ".py", ".rs", ".ts":
				var parseErr error
				nodes, edges, parseErr = tsParser.ParseFile(ctx, filePath)
				if parseErr != nil {
					return fmt.Errorf("parse %s: %w", filePath, parseErr)
				}
			default:
				return nil
			}

			if len(nodes) == 0 && len(edges) == 0 {
				return nil
			}

			fmt.Printf("Indexing %s...\n", filePath)
			if err := store.SaveGraph(ctx, nodes, edges); err != nil {
				return fmt.Errorf("persist graph for %s: %w", filePath, err)
			}

			return nil
		})

		if err != nil {
			return err
		}

		fmt.Println("Indexing complete.")

		// Generate metadata files
		stats, err := store.GetStats(ctx)
		if err != nil {
			return fmt.Errorf("failed to get stats for metadata: %w", err)
		}

		if err := generateMetadata(path, stats); err != nil {
			return fmt.Errorf("failed to generate metadata: %w", err)
		}

		return nil
	},
}

func generateMetadata(path string, stats *contracts.Stats) error {
	leaDir := filepath.Join(path, ".lea")

	// WORKSPACE.md
	workspaceContent := fmt.Sprintf(`# Workspace Structural Metadata

Generated By: Lea
Version: 0.1.0

## Repository Statistics

Languages:
%s

Nodes:
%d

Edges:
%d

## Capabilities
- Symbol Discovery
- Dependency Analysis
- Call Graph Traversal
- Impact Analysis
- Architecture Validation
`, formatLanguages(stats.Languages), stats.NodesCount, stats.EdgesCount)

	if err := os.WriteFile(filepath.Join(leaDir, "WORKSPACE.md"), []byte(workspaceContent), 0644); err != nil {
		return err
	}

	// AGENT.md
	agentContent := `# Structural Reasoning Protocol

This repository contains a deterministic structural graph generated by Lea.

Before inspecting source files:

1. Discover the relevant symbol.
2. Inspect structural dependencies.
3. Analyze execution paths.
4. Retrieve minimal context.
5. Apply modifications.
6. Validate architecture constraints.

Avoid:

- Full repository scans.
- Recursive grep exploration.
- Reading unrelated files.

Prefer structural navigation whenever possible.
`
	if err := os.WriteFile(filepath.Join(leaDir, "AGENT.md"), []byte(agentContent), 0644); err != nil {
		return err
	}

	// .agent-manifesto.md
	manifestoContent := `# Lea Agent Manifesto

## Purpose
This manifesto defines how AI agents should interact with this repository using Lea.

## Workflow
1. **Discover**: Use ` + "`" + `lea symbols` + "`" + ` to find relevant symbols.
2. **Reason**: Use ` + "`" + `lea impact` + "`" + ` and ` + "`" + `lea flow` + "`" + ` to understand structural relationships and execution paths.
3. **Context**: Use ` + "`" + `lea context` + "`" + ` with a budget to retrieve minimal necessary code context.
4. **Modify**: Apply code changes.
5. **Validate**: Use ` + "`" + `lea violations` + "`" + ` to ensure architectural integrity.

## Principles
- **Structure First**: Never read files blindly. Use the graph.
- **Token Efficiency**: Use budget-aware context generation.
- **Deterministic Reasoning**: Trust the call graph over semantic search when tracing execution.
`
	if err := os.WriteFile(filepath.Join(leaDir, ".agent-manifesto.md"), []byte(manifestoContent), 0644); err != nil {
		return err
	}

	fmt.Printf("Generated metadata in %s\n", leaDir)
	return nil
}

func formatLanguages(langs []string) string {
	if len(langs) == 0 {
		return "- None"
	}
	var res []string
	for _, l := range langs {
		res = append(res, fmt.Sprintf("- %s", l))
	}
	return strings.Join(res, "\n")
}

func getModuleName(path string) string {
	goModPath := filepath.Join(path, "go.mod")
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return ""
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func init() {
	rootCmd.AddCommand(indexCmd)
}
